# Generated by Django 3.2.7 on 2022-11-02 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_readerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LibrarianProfile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+41524204242', max_length=30, region=None, verbose_name='Phone Number')),
                ('about_me', models.TextField(blank=True, default='say something about yourself', null=True, verbose_name='About me')),
                ('profile_photo', models.ImageField(blank=True, default='/profile_default.png', null=True, upload_to='', verbose_name='Profile Photo')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20, null=True, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(default='CO', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Medellin', max_length=180, verbose_name='City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
