# front/docker-compose.yml
version: '2'
services:
  frontend-react:
    container_name: biblio_app_frontend
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    restart: on-failure
    # ports:
    #   - '8081:5173'
    volumes:
      - .:/frontend
      - /frontend/node_modules
    networks:
      - backend_frontend_biblio

  nginx:
    container_name: biblio_app_frontend_nginx
    restart: always
    depends_on:
      - frontend-react
    volumes:
      - backend_static_volume_biblio:/backend/staticfiles
      - backend_media_volume_biblio:/backend/mediafiles
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    networks:
      - backend_frontend_biblio

networks:
  backend_frontend_biblio:
    external: true

volumes:
  backend_static_volume_biblio:
    external: true
  backend_media_volume_biblio:
    external: true
