# Generated by Django 3.2.7 on 2022-11-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221102_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
            ],
            options={
                'verbose_name': 'Librarian',
                'verbose_name_plural': 'Librarians',
                'ordering': ['-date_joined'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
            ],
            options={
                'verbose_name': 'Reader',
                'verbose_name_plural': 'Readers',
                'ordering': ['-date_joined'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
