# Generated by Django 3.2.7 on 2022-10-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('LIBRARIAN', 'librarian'), ('READER', 'reader'), ('OTHER', 'other')], default='READER', max_length=20, verbose_name='Role'),
        ),
    ]
