# Generated by Django 3.2.7 on 2022-10-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_librarian',
            field=models.BooleanField(default=False, verbose_name='Is Librarian'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_reader',
            field=models.BooleanField(default=False, verbose_name='Is Reader'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('LIBRARIAN', 'librarian'), ('READER', 'reader')], default='READER', max_length=20),
        ),
    ]
