# Generated by Django 3.2.7 on 2022-10-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221028_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_librarian',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_reader',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('LIBRARIAN', 'librarian'), ('READER', 'reader'), ('OTHER', 'other')], default='READER', max_length=20),
        ),
    ]
